[build]
publish = "home/public"
command = "cd home; hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.89.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "cd home; hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.89.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "cd home; hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.89.0"

[context.branch-deploy]
command = "cd home; hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.89.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[redirects]]
from = "/npmjs/*"
to = "/npmjs/"
status = 200
